[project]
name = "friends-birthday"
version = "0.1.0"
description = ""
authors = [
    {name = "Алдар Дондоков",email = "dondokovabnsu@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram (>=3.22.0,<4.0.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "aiosql (>=13.4,<14.0)",
    "aiosqlite (>=0.21.0,<0.22.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "apscheduler (>=3.11.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
